Class {
	#name : #TCODRect,
	#superclass : #Object,
	#instVars : [
		'x1',
		'y1',
		'x2',
		'y2'
	],
	#category : #'LibtcodSt-Tutorial'
}

{ #category : #accessing }
TCODRect >> x1 [
	^ x1
]

{ #category : #accessing }
TCODRect >> x1: anObject [
	x1 := anObject
]

{ #category : #accessing }
TCODRect >> x2 [
	^ x2
]

{ #category : #accessing }
TCODRect >> x2: anObject [
	x2 := anObject
]

{ #category : #accessing }
TCODRect >> y1 [
	^ y1
]

{ #category : #accessing }
TCODRect >> y1: anObject [
	y1 := anObject
]

{ #category : #accessing }
TCODRect >> y2 [
	^ y2
]

{ #category : #accessing }
TCODRect >> y2: anObject [
	y2 := anObject
]
